# Generated by Django 3.1.1 on 2020-09-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24)),
                ('apellido', models.CharField(max_length=24)),
                ('carne', models.IntegerField()),
            ],
        ),
    ]
